// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC10TtiQ5hE3F2maWKELfttzult6Zc1Hto',
    appId: '1:162171865470:web:09a5b08e66454c0f2a4b2f',
    messagingSenderId: '162171865470',
    projectId: 'herody-c9e76',
    authDomain: 'herody-c9e76.firebaseapp.com',
    storageBucket: 'herody-c9e76.firebasestorage.app',
    measurementId: 'G-GC9D3HLMG2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBscVhXfbstWhx9lS4MjR8JbbUuRtGhKQU',
    appId: '1:162171865470:android:d326241f705f23712a4b2f',
    messagingSenderId: '162171865470',
    projectId: 'herody-c9e76',
    storageBucket: 'herody-c9e76.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZohuqcUPmma1Kg7FaXmPoeIZLxxTSstk',
    appId: '1:162171865470:ios:4168848ab24f335e2a4b2f',
    messagingSenderId: '162171865470',
    projectId: 'herody-c9e76',
    storageBucket: 'herody-c9e76.firebasestorage.app',
    iosBundleId: 'com.example.herody',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZohuqcUPmma1Kg7FaXmPoeIZLxxTSstk',
    appId: '1:162171865470:ios:4168848ab24f335e2a4b2f',
    messagingSenderId: '162171865470',
    projectId: 'herody-c9e76',
    storageBucket: 'herody-c9e76.firebasestorage.app',
    iosBundleId: 'com.example.herody',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC10TtiQ5hE3F2maWKELfttzult6Zc1Hto',
    appId: '1:162171865470:web:e95656d1933a56132a4b2f',
    messagingSenderId: '162171865470',
    projectId: 'herody-c9e76',
    authDomain: 'herody-c9e76.firebaseapp.com',
    storageBucket: 'herody-c9e76.firebasestorage.app',
    measurementId: 'G-NKP4NB4DLK',
  );
}
